// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // ProductModelProductDescription
    ///<summary>
    /// Cross-reference table mapping product descriptions and the language the description is written in.
    ///</summary>
    [Table("ProductModelProductDescription", Schema = "SalesLT")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class SalesLT_ProductModelProductDescription
    {

        ///<summary>
        /// Primary key. Foreign key to ProductModel.ProductModelID.
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ProductModelID", Order = 1, TypeName = "int")]
        [Index(@"PK_ProductModelProductDescription_ProductModelID_ProductDescriptionID_Culture", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Product model ID")]
        public int ProductModelId { get; set; } // ProductModelID (Primary key)

        ///<summary>
        /// Primary key. Foreign key to ProductDescription.ProductDescriptionID.
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ProductDescriptionID", Order = 2, TypeName = "int")]
        [Index(@"PK_ProductModelProductDescription_ProductModelID_ProductDescriptionID_Culture", 2, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Product description ID")]
        public int ProductDescriptionId { get; set; } // ProductDescriptionID (Primary key)

        ///<summary>
        /// The culture for which the description is written
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Culture", Order = 3, TypeName = "nchar")]
        [Index(@"PK_ProductModelProductDescription_ProductModelID_ProductDescriptionID_Culture", 3, IsUnique = true, IsClustered = true)]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(6)]
        [StringLength(6)]
        [Key]
        [Display(Name = "Culture")]
        public string Culture { get; set; } // Culture (Primary key) (length: 6)

        [Column(@"rowguid", Order = 4, TypeName = "uniqueidentifier")]
        [Index(@"AK_ProductModelProductDescription_rowguid", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [Display(Name = "Rowguid")]
        public System.Guid Rowguid { get; set; } // rowguid

        ///<summary>
        /// Date and time the record was last updated.
        ///</summary>
        [Column(@"ModifiedDate", Order = 5, TypeName = "datetime")]
        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Modified date")]
        public System.DateTime ModifiedDate { get; set; } // ModifiedDate

        // Foreign keys

        /// <summary>
        /// Parent SalesLT_ProductDescription pointed by [ProductModelProductDescription].([ProductDescriptionId]) (FK_ProductModelProductDescription_ProductDescription_ProductDescriptionID)
        /// </summary>
        [ForeignKey("ProductDescriptionId"), Required] public virtual SalesLT_ProductDescription SalesLT_ProductDescription { get; set; } // FK_ProductModelProductDescription_ProductDescription_ProductDescriptionID

        /// <summary>
        /// Parent SalesLT_ProductModel pointed by [ProductModelProductDescription].([ProductModelId]) (FK_ProductModelProductDescription_ProductModel_ProductModelID)
        /// </summary>
        [ForeignKey("ProductModelId"), Required] public virtual SalesLT_ProductModel SalesLT_ProductModel { get; set; } // FK_ProductModelProductDescription_ProductModel_ProductModelID

        public SalesLT_ProductModelProductDescription()
        {
            Rowguid = System.Guid.NewGuid();
            ModifiedDate = System.DateTime.Now;
        }
    }

}
// </auto-generated>
