// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Entities
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // vGetAllCategories
    [Table("vGetAllCategories", Schema = "SalesLT")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class SalesLT_VGetAllCategory
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ParentProductCategoryName", Order = 1, TypeName = "nvarchar")]
        [Required(AllowEmptyStrings = true)]
        [MaxLength(50)]
        [StringLength(50)]
        [Key]
        [Display(Name = "Parent product category name")]
        public string ParentProductCategoryName { get; set; } // ParentProductCategoryName (Primary key) (length: 50)

        [Column(@"ProductCategoryName", Order = 2, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Product category name")]
        public string ProductCategoryName { get; set; } // ProductCategoryName (length: 50)

        [Column(@"ProductCategoryID", Order = 3, TypeName = "int")]
        [Display(Name = "Product category ID")]
        public int? ProductCategoryId { get; set; } // ProductCategoryID
    }

}
// </auto-generated>
