// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Configurations
{
    using Entities;
    using Interfaces;
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // Customer
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class SalesLT_CustomerConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SalesLT_Customer>
    {
        public SalesLT_CustomerConfiguration()
            : this("SalesLT")
        {
        }

        public SalesLT_CustomerConfiguration(string schema)
        {
            Property(x => x.Title).IsOptional();
            Property(x => x.MiddleName).IsOptional();
            Property(x => x.Suffix).IsOptional();
            Property(x => x.CompanyName).IsOptional();
            Property(x => x.SalesPerson).IsOptional();
            Property(x => x.EmailAddress).IsOptional();
            Property(x => x.Phone).IsOptional();
            Property(x => x.PasswordHash).IsUnicode(false);
            Property(x => x.PasswordSalt).IsUnicode(false);
        }
    }

}
// </auto-generated>
