// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Configurations
{
    using Entities;
    using Interfaces;
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;

    // Product
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.2.0")]
    public class SalesLT_ProductConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SalesLT_Product>
    {
        public SalesLT_ProductConfiguration()
            : this("SalesLT")
        {
        }

        public SalesLT_ProductConfiguration(string schema)
        {
            Property(x => x.Color).IsOptional();
            Property(x => x.StandardCost).HasPrecision(19,4);
            Property(x => x.ListPrice).HasPrecision(19,4);
            Property(x => x.Size).IsOptional();
            Property(x => x.Weight).IsOptional().HasPrecision(8,2);
            Property(x => x.ProductCategoryId).IsOptional();
            Property(x => x.ProductModelId).IsOptional();
            Property(x => x.SellEndDate).IsOptional();
            Property(x => x.DiscontinuedDate).IsOptional();
            Property(x => x.ThumbNailPhoto).IsOptional();
            Property(x => x.ThumbnailPhotoFileName).IsOptional();

        }
    }

}
// </auto-generated>
